apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-zfkc
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/dc-metro-map-zfkc@sha256:21abdaa06b2de9b67ac94b943a9b06ed41cfb8a885db94b75b9a84e0db803240
        name: my-nodejs
        resources: {}
status: {}
